### ISSUE TITLE
Solve Bouncing Balls Challenge

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/Bouncing-Balls#1]
https://www.codewars.com/kata/5544c7a5cb454edb3c000047/train/javascript

**Comment by kimiaRahimi** [comment]
@FarshadJanmohammadi سلام وقت بخیر خسته نباشید من متوجه این تسک نشدم ممنون میشم توضیح مختصر دربارش بهم بدین...
